export enum AppIcons {
  CAMERA = 'camera',
  MEDIA = 'images',
  NIGHT = 'moon',
  DAY = 'sunny',
  ARROW_DOWN_CIRCLE = 'arrow-down-circle',
  FORUM = 'chatbox',
  CLOSE = 'close',
  PENCIL = 'pencil',
  MENU_X = 'ellipsis-horizontal',
  ARROW_BACK = 'arrow-back',
  GPS = 'locate',
  PIN = 'pin',
  LINK = 'link',
  SEND = 'send',
  EDIT = 'create',
  PERSON = 'person-circle',
  PERSON_ADD = 'person-add',
  REPORT = 'flag',
  DELETE = 'trash',
  SETTINGS = 'cog',
  TIME = 'time',
  HOT = 'flame',
  FILTER = 'filter',
  SEARCH = 'search',
}
